require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - .gems/**/*
    - bin/**/*
    - config/**/*
    - db/**/*
    - log/**/*
    - public/**/*
    - tmp/**/*
    - vendor/**/*
    - spec/rails_helper.rb
    - spec/spec_helper.rb
    - spec/**/*
    - config.ru
    - Rakefile
    - node_modules/**/*

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
